config/routes.rb
Rails.application.routes.draw do
  resources :schools
  # Specify only specific actions
  # resources :courses, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  resources :courses

  # Single route to search action and view
  get 'search', to: 'courses#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :school
end

app/models/school.rb
class School < ApplicationRecord
  # Association to link to many courses
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
# Controller are the plural of the Model name e.g. Courses not Course
  # Refactoring finding our course via params id
  before_action :set_course, only: [:edit, :update, :show, :destroy]

  # Index action goes to views/courses/index.html.erb
  def index
    # Create instance variables @coures which is available in my index view
    # Course refers to model
    # .all is a method on Rails models to get all records
    @courses = Course.all
  end

  # New action goes to views/courses/new.html.erb
  def new
    # Creating a new empty Course object
    @course = Course.new
  end

  # Create action creates a new course record associated with a School
  def create
    # Find first school record
    school = School.find(1)
    # Create course without association
    # @course = Course.new(course_params)

    # Create course based on school -> courses association
    @course = school.courses.build(course_params)

    if @course.save
      # Show successful flash message and redirect to courses list
      flash[:notice] = "Course was successfully added."
      redirect_to courses_path
    else
      # Render the new template
      render :new
    end
  end

  # Edit action goes to views/courses/edit.html.erb
  def edit
    # Find course with params id
    # This find is refactored into before_action
    # @course = Course.find(params[:id])
  end

  def update
    # Find course with params id
    # This find is refactored into before_action
    # @course = Course.find(params[:id])

    # Update course
    if @course.update(course_params)
      # Show flash that course is updated
      flash[:notice] = "Course successfully updated!"
      # Redirect to Courses index
      redirect_to courses_path
    else
      # Render edit page if updating returns false
      render :edit
    end
  end

  # Show action goes to views/courses/show.html.erb
  def show
    # This find is refactored into before_action
    # @course = Course.find(params[:id])
  end

  def destroy
    # Destroy course and redirect to courses path
    @course.destroy
    flash[:notice] = "Course removed."
    redirect_to courses_path
  end

  def search
    
  end

  private

  def course_params
    params.require(:course).permit(:subject, :course_number, :description)
  end

  # Set course method through params via before_action
  def set_course
    @course = Course.find(params[:id])
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # This is a filter that is called before the following actions
  # It calls set_school which is a method in this controller
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  # Example of empty after_action
  after_action :some_method

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/:id/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)
    # See sanitized params in server
    puts school_params

    respond_to do |format|
      if @school.save
        format.html { redirect_to school_path(@school), notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      # Simple debugging to see params, shows up in my server
      puts params
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :location)
    end

    def some_method
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>
      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :course_number %>
    <%= f.text_field :course_number %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Course Number</th>
      <th>Description</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.subject %></td>
        <td><%= course.course_number %></td>
        <td><%= course.description %></td>
        <td><%= link_to "Edit Course", edit_course_path(course) %></td>
        <td><%= link_to "Show Course", course_path(course) %></td>
        <td><%= link_to "Destroy Course", course_path(course), method: :delete %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Course" , new_course_path %>
<br>
<br>
<%= link_to "Search Course", search_path %>

<br>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/search.html.erb
<h1>Search for your favourite course</h1>

<!-- Challenge: Add a search form to search courses by ID or name -->

<!-- Challenge #2: Render search with a different layout -->

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @course.subject %>
</p>

<p>
  <strong>Course Number:</strong>
  <%= @course.course_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseKeeper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for(school) do |f| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.location %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @school.location %>
</p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>